# Generated by Django 2.1.1 on 2018-09-18 14:29

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20180918_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='dataInicio',
            field=models.DateField(default=datetime.datetime(2018, 9, 18, 14, 29, 12, 414676, tzinfo=utc)),
        ),
    ]
