# Generated by Django 2.1.1 on 2018-09-18 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20180918_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='dataInicio',
            field=models.DateField(default=datetime.datetime(2018, 9, 18, 14, 36, 3, 867970, tzinfo=utc)),
        ),
    ]
