# Generated by Django 2.1.1 on 2018-09-18 17:02

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20180918_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='dataInicio',
            field=models.DateField(default=datetime.datetime(2018, 9, 18, 17, 2, 32, 390862, tzinfo=utc)),
        ),
    ]
