# Generated by Django 2.1.1 on 2018-09-29 00:11

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20180918_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', ckeditor_uploader.fields.RichTextUploadingField()),
                ('alternativaA', models.CharField(max_length=30)),
                ('alternativaB', models.CharField(max_length=30)),
                ('alternativaC', models.CharField(max_length=30)),
                ('alternativaD', models.CharField(max_length=30)),
                ('alternativaE', models.CharField(max_length=30)),
                ('correta', models.CharField(choices=[('Alternativa A', 'Alternativa A'), ('Alternativa B', 'Alternativa B'), ('Alternativa C', 'Alternativa C'), ('Alternativa D', 'Alternativa D'), ('Alternativa E', 'Alternativa E')], max_length=10)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Aula')),
            ],
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='dataInicio',
            field=models.DateField(default=datetime.datetime(2018, 9, 29, 0, 11, 38, 256535, tzinfo=utc)),
        ),
    ]
