# Generated by Django 2.1.1 on 2018-09-29 00:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20180928_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='dataInicio',
            field=models.DateField(default=datetime.datetime(2018, 9, 29, 0, 14, 33, 309854, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='correta',
            field=models.CharField(choices=[('Alternativa A', 'Alternativa A'), ('Alternativa B', 'Alternativa B'), ('Alternativa C', 'Alternativa C'), ('Alternativa D', 'Alternativa D'), ('Alternativa E', 'Alternativa E')], max_length=13),
        ),
    ]
