# Generated by Django 2.1.1 on 2018-10-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20180928_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='nome',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
