# Generated by Django 2.1.1 on 2018-10-04 14:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20181001_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('answer_text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlternativeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=500)),
                ('state', models.BooleanField()),
                ('level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Alternative')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='alternativaA',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='alternativaB',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='alternativaC',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='alternativaD',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='alternativaE',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.Activity')),
                ('difficulty', models.IntegerField()),
                ('user_exercise', models.BooleanField()),
            ],
            bases=('portal.activity',),
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.Activity')),
                ('title', models.CharField(max_length=85)),
                ('level', models.IntegerField()),
            ],
            bases=('portal.activity',),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Activity'),
        ),
        migrations.AddField(
            model_name='alternative',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AlternativeCategory'),
        ),
        migrations.AddField(
            model_name='alternative',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Step'),
        ),
        migrations.AddField(
            model_name='activity',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Subject'),
        ),
        migrations.AddField(
            model_name='step',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Exercise'),
        ),
    ]
