# Generated by Django 2.1.1 on 2018-10-13 21:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20181012_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='answer_ckeditor',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='answer',
            field=models.CharField(max_length=500),
        ),
    ]
