# Generated by Django 2.1.1 on 2018-10-13 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_auto_20181013_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternative',
            name='answer_ckeditor',
        ),
    ]
