# Generated by Django 2.1.1 on 2018-10-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_remove_alternative_answer_ckeditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='answer_ckeditor',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
