# Generated by Django 2.1.1 on 2018-10-25 18:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_auto_20181013_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('sequence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StructureCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Curriculum')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Structure')),
            ],
        ),
        migrations.AlterField(
            model_name='alternative',
            name='answer_ckeditor',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=500),
        ),
    ]
