# Generated by Django 2.1.1 on 2018-11-12 12:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_auto_20181025_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85)),
            ],
        ),
        migrations.CreateModel(
            name='TutorStep',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.Step')),
                ('difficulty', models.IntegerField()),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Evidence')),
            ],
            bases=('portal.step',),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='answer_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=500),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=500),
        ),
    ]
