# Generated by Django 2.1.1 on 2018-11-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_auto_20181113_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Activity')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Module')),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='tutorstep',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
