# Generated by Django 2.1.1 on 2018-11-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_auto_20181116_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulecurriculum',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='modulecurriculum',
            name='module',
        ),
        migrations.DeleteModel(
            name='ModuleCurriculum',
        ),
    ]
