# Generated by Django 2.1.1 on 2018-11-27 21:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_auto_20181116_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternative',
            name='answer_ckeditor',
        ),
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1500),
        ),
    ]
