# Generated by Django 2.1.1 on 2018-11-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_auto_20181127_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='answer_ck',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
